"""Storage adapter protocol — interface for ContextPack persistence."""

from __future__ import annotations

from typing import Optional, Protocol

from ..format.context_pack import ContextPack
from ..format.run_metadata import RunMetadata


class StorageAdapter(Protocol):
    def write_step(self, pack: ContextPack) -> None: ...
    def complete_run(self, run_meta: RunMetadata) -> None: ...
    def list_runs(self, limit: int = 50, offset: int = 0) -> list[RunMetadata]: ...
    def get_run(self, run_id: str) -> Optional[RunMetadata]: ...
    def get_steps(self, run_id: str) -> list[ContextPack]: ...
    def get_step(self, run_id: str, step_id: str) -> Optional[ContextPack]: ...
